// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn83fd027b0r7JQ-UXnfmqS4dnPakMUac',
    appId: '1:702265010784:web:20b6729dc89bba4634f105',
    messagingSenderId: '702265010784',
    projectId: 'homie-6a367',
    authDomain: 'homie-6a367.firebaseapp.com',
    storageBucket: 'homie-6a367.appspot.com',
    measurementId: 'G-KBX12G1CYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJIPVun6D5JDnHxvrtlUzJqwiBxdOUXeQ',
    appId: '1:702265010784:android:105c763634b57bfc34f105',
    messagingSenderId: '702265010784',
    projectId: 'homie-6a367',
    storageBucket: 'homie-6a367.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGkbMIUDgOSlINUW1nhOAW2UQNTr2WKCo',
    appId: '1:702265010784:ios:9832bb10750b105634f105',
    messagingSenderId: '702265010784',
    projectId: 'homie-6a367',
    storageBucket: 'homie-6a367.appspot.com',
    iosBundleId: 'com.example.homie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGkbMIUDgOSlINUW1nhOAW2UQNTr2WKCo',
    appId: '1:702265010784:ios:9832bb10750b105634f105',
    messagingSenderId: '702265010784',
    projectId: 'homie-6a367',
    storageBucket: 'homie-6a367.appspot.com',
    iosBundleId: 'com.example.homie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn83fd027b0r7JQ-UXnfmqS4dnPakMUac',
    appId: '1:702265010784:web:90d027b6c15bd04034f105',
    messagingSenderId: '702265010784',
    projectId: 'homie-6a367',
    authDomain: 'homie-6a367.firebaseapp.com',
    storageBucket: 'homie-6a367.appspot.com',
    measurementId: 'G-X8B0ENS5DS',
  );
}
